package dependencies

object Version {

    // android configuration
    const val buildTools = "28.0.3"
    const val compileSdk = 29
    const val minSdk = 21
    const val targetSdk = 29
    const val versionCode = 3
    const val versionName = "1.0.0"

    // Libraries
    const val supportLib = "28.0.0"
    const val recyclerView = "1.0.0"
    const val androidx = "1.0.0"
    const val androidx_112 = "1.1.3"
    const val androidx_100beta01 = "1.0.0-beta01"
    const val assertJVersion = "3.2.0"
    const val circleImageView = "3.1.0"
    const val componentManager = "2.0.1"
    const val firebaseBOM = "25.12.0"
    const val firebaseCore = "17.4.4"
    const val firebaseAnalytics = "18.0.0"
    const val firebasePref = "19.0.8"
    const val firebaseCrashlytics = "17.2.1"
    const val firebaseCrashlyticsGradle = "2.2.1"
    const val firebaseRemoteConfig = "19.1.4"
    const val materialDesign = "1.2.1"
    const val mockito = "1.10.19"
    const val mockitoInline = "2.24.5"
    const val mockWebServer = "4.9.0"
    const val mpAndroidChart = "3.1.0"
    const val navigation = "2.3.0"
    const val dagger2 = "2.21"
    const val lifecycleVersion = "2.0.0"
    const val javaxInject = "1"
    const val javaxAnnotation = "1.0"
    const val jacoco = "0.16.0"
    const val jodaTime = "2.10.6"
    const val jvmTarget = "1.8"
    const val parcelerVersion = "1.1.12"
    const val permissionDispatcher = "4.8.0"
    const val permissionAnnotation = "4.8.0"
    const val picasso = "2.71828"
    const val gradleVersion = "3.5.0"
    const val googleServices = "4.3.3"
    const val ktx = "1.1.0"
    const val ktLint = "0.35.0"
    const val kotlinVersion = "1.3.50"
    const val legacySupport = "1.0.0"
    const val dokkaVeresion = "0.9.18"
    const val espresso = "3.1.0"
    const val glide = "4.9.0"
    const val gson = "2.8.5"
    const val androidXJunit = "1.1.2"
    const val kotlin = "1.3.31"
    const val lifecycle = "1.1.1"
    const val playCore = "1.7.0"
    const val reactiveNetwork = "3.0.3"
    const val retrofit = "2.5.0"
    const val retrofit_log = "3.10.0"
    const val roboElectric = "3.4.2"
    const val room = "2.2.5"
    const val rules = "1.1.0"
    const val runner = "1.1.0"
    const val rx = "2.1.0"
    const val rxAndroid = "2.0.1"
    const val rxRelay = "2.0.0"
    const val rxBinding = "3.0.0"
    const val stetho = "1.5.1"
    const val timber = "4.7.1"
    const val message = "21.0.0"
    const val play_services = "18.1.0"
    const val play_plus = "17.0.0"
    const val location = "17.1.0"
    const val expandableLayout = "2.9.2"
    const val progressWheel = "1.1.5"
    const val imageSlider = "1.4.0"

    // plugins versions
    const val detektVersion = "1.9.1"
}
