name: Android CI

on: pull_request

jobs:
  # Running linting using detekt,ktlint
  lint:
    name: Running lints
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Running Ktlint
        run: bash ./gradlew ktlint --stacktrace

      - name: Running detekt
        run: bash ./gradlew detekt --stacktrace

  # Running Unit Test Cases
  unitTest:
    needs: lint
    name: Running Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace